import Header from '@/components/commons/header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/commons/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Gospel voice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
